# Generated by Django 2.2.1 on 2019-05-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('sourcename', models.CharField(max_length=64)),
                ('sourceversion', models.CharField(max_length=64)),
                ('totaldistance', models.FloatField()),
                ('totaldistanceunit', models.CharField(max_length=64)),
                ('duration', models.FloatField()),
                ('durationunit', models.CharField(max_length=64)),
                ('totalenergyburned', models.FloatField()),
                ('totalenergyburnedunit', models.CharField(max_length=64)),
                ('workoutactivitytype', models.CharField(max_length=64)),
            ],
        ),
    ]
